spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/chatroom'
    username: 'chat'
    password: 'room'
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
