server:
  port: 8080
spring:
  datasource:
    url: 'jdbc:postgresql://db:5432/chatroom'
    username: 'chat'
    password: 'room'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect