server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:chatroom
    username: 'chat'
    password: 'room'
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  jackson:
    default-property-inclusion: non_null
